### ISSUE TITLE
FireEye AX isn't closing sessions

### ISSUE THREAD

**Issue by cygnetix** [InQuest/python-sandboxapi#3]
Greetings!

We identified an issue where users were getting errors when trying to logon to the AX along the lines of `Login failed: Too many web logins, 200 allowed`.

I've referred to the AX documentation and found that it states: `After you have completed your requests, you should log out using the logout command` ... `The Web Services API has a default limit of 100 concurrent open sessions`.

I've added some code and we'll wait and see if this resolves the issue. I'll send a PR shortly.

**Comment by cmmorrow** [comment]
You're right, logout needs to be called. I'm not seeing this in master, so I'll submit a PR to add your code. Thanks for contributing!

**Comment by cmmorrow** [comment]
This is addressed in PR #12 and will be included in release 1.5.

**Comment by cmmorrow** [comment]
This issue is addressed in release 1.5.1.
