### ISSUE TITLE
cuckoo score TypeError handling

### ISSUE THREAD

**Issue by proc-freq** [InQuest/python-sandboxapi#4]
I'm sometimes running into...
```
File "/usr/local/lib/python3.5/dist-packages/sandboxapi/cuckoo.py", line 197, in score
    score = report['malscore']
TypeError: byte indices must be integers or slices, not str
```
when an analysis is being scored and my python script is running. I'm assuming just adding
```
        except TypeError as e:
            raise sandboxapi.SandboxError(e)
```
to the score function would resolve the issue.

I've modified my local copy of cuckoo.py and am attempting to test my local change. If I can validate this resolves the issue I'll submit a PR.

**Comment by proc-freq** [comment]
Submitted PR to add requested error handling. #5

**Comment by cmmorrow** [comment]
I've merged the change to master and will include it in the 1.5 release soon.
