### ISSUE TITLE
Falcon unavailable issue

### ISSUE THREAD

**Issue by apolkosnik** [InQuest/python-sandboxapi#8]
It looks like there is a need to tweak the is_available() for Falcon a bit for the off prem.

>>> b = requests.get('https://example.falcon-sandbox.com/api/v2/system/heartbeat', proxies=proxies, headers=headers)
>>> print b
<Response [403]> 
>>> print(b.content)
{"message":"This endpoint is available on in on-premise version"}

changing the endpoint to "/system/version" should work around this issue.

**Comment by cmmorrow** [comment]
Addressed this issue in PR #11 and will target to include it in release 1.5.

**Comment by cmmorrow** [comment]
This issue is addressed in release 1.5.1.
